---
title: "Data 605 Week 10 Discussion"
author: "Anthony Pagan"
date: "April 03, 2019"
output:
  html_document:
    df_print: paged
  word_document: default
---
Page 423 #8 
In Example 11.13 (Drunkard's Walk) of this section, assume that the probability of a step to the right is 2/3, and a step to the left is 1/3. Find N, Nc, and NR. Compare these with the results of Example 11.15.

**Example 11.13**
```{r}
Q<-matrix(c(0,.5,0,.5,0,.5,0,.5,0),3,3, byrow =TRUE)
I<-matrix(c(1,0,0,0,1,0,0,0,1),3,3,byrow=TRUE)
R<-matrix(c(.5,0,0,0,0,.5),3,2,byrow=TRUE)
N<-solve(I-Q)
c<-matrix(c(1,1,1),3,1, byrow=TRUE)
Nc<-N%*%c
NR<-N%*%R
N
Nc
NR

```

**Example 11.15**

```{r}
Q<-matrix(c(0,.33,0,.67,0,.33,0,.67,0),3,3, byrow =TRUE)
I<-matrix(c(1,0,0,0,1,0,0,0,1),3,3,byrow=TRUE)
R<-matrix(c(.33,0,0,0,0,.67),3,2,byrow=TRUE)
N<-solve(I-Q)
c<-matrix(c(1,1,1),3,1, byrow=TRUE)
Nc<-N%*%c
NR<-N%*%R

```

**N is:**
```{r echo=FALSE, message=FALSE, warning=FALSE}
round(N,2)
```

**Nc is:**
```{r echo=FALSE, message=FALSE, warning=FALSE}
round(Nc,2)
```

**NR is:**
```{r echo=FALSE, message=FALSE, warning=FALSE}
round(NR,2)
```