---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---


```{r}
a <- matrix(c(1,0,2,4,3,2),nrow=2, ncol=3)
a
b<- matrix(c(1,0,1,1,2,2),nrow=2, ncol=3)
b
2*a - 3*b

```

```{r}
library(matlib)
a <- matrix(c(2,2, 3,2, 1, -1), nrow=3, ncol=2,byrow=TRUE)
a
b <- matrix(c(8, 4, 2), nrow = 3, ncol = 1, byrow = TRUE)
b
echelon(a, b)

x <- showEqn(a, b)
x

plotEqn(a,b)
```

```{r}
A<- matrix(seq(from=1, to=6), nrow=2, byrow=T)
B<- matrix(seq(from=12, to=7), nrow=2)
A + B
A%*%t(B)

t(A)%*%B
```

```{r}
A<-matrix(c(-1,8,4,1,-5,3,0,9,-1),nrow=3, ncol=3)
B<-matrix(c(11,2,-14,4,-17,-12,9,0,5),nrow=3, ncol=3)
A
B
(B-A) /3

A <-matrix(c(7,12,7,-1,14,9),nrow=3, ncol=2)
B <-matrix(c(3,14,-8,-6,19,1),nrow=3, ncol=2)
A
B
(B+A)*6
```

```{r}
Y <-matrix(c(2,1,-1,2),nrow=2, ncol=2)
Z <-matrix(c(1,0,1,4,-3,4),nrow=2, ncol=3)
Y
Z
Y%*%Z
Y
t(Y)  
```


```{r}
A <-matrix(c(1,3,2,4),nrow=2, ncol=2)
C <-matrix(c(1,0,0,1),nrow=2,ncol=2)

echelon(A)
k<-eigen(A,C)
showEqn(A)
x

plotEqn(A,C)

A
e<-eigen(A)
e[1]
e
```


det(	-1	2
        -6	6
	-	 
	    λ 	0
        0	λ

    ) 

=  (-1- λ )* (6 – λ) – (-6) * 2 = 0
=  (-1- λ )* (6 – λ) + 12= 0
= λ^2 -6 -6λ+λ+12 = 0
= λ^2 -5λ+6 = 0
= (λ-3) * (λ -2) = 0


Polynomial equation = λ^2 -5λ+6 = 0
eigan values = λ1 = 3 and λ2 = 2

```{r}
library(matlib)
A<-matrix(c(1,4,3,2),2,2,byrow=TRUE)
A
B<-matrix(c(2,1))
B
A%*%B
det(A,B)
Av<-eigen(A)
e.values<-round(Av$values,1)
echelon(A, reduce=FALSE)
A.rank<-R(A)
Av<-eigen(A)
e.values<-round(Av$values,1)
e.vectors<-round(Av$vectors,1)
e.values
e.vectors
R(A)
det(A)
solve(A)
C<-matrix(c(e.values[1],0,0,e.values[1]),2,2,byrow=TRUE)
C.v<-A-C
C.v[1,1]+C.v[1,2]
C.v[2,1]+C.v[2,2]

A<-matrix(c(5,5,-1,7),2,2,byrow=TRUE)
X <- A%*%t(A)
Y <- t(A)%*%A
X
Y
e.Y<-eigen(Y)
e.X<-eigen(X)
e.Y$values
e.X$values
e.X
e.Y
svd(A)

library(matlib)
inv(A)
A
```
$\mathbf\lambda^3$\ * 4 $\mathbf\lambda^2$\
