---
title: "Data606HW8"
author: "Anthony Pagan"
date: "December 08, 2018"
output: html_document
---

8.2 Baby weights, Part II. Exercise 8.1 introduces a data set on birth weight of babies. Another variable we consider is parity, which is 0 if the child is the first born, and 1 otherwise. The summary table below shows the results of a linear regression model for predicting the average birth weight of babies, measured in ounces, from parity.

(a) Write the equation of the regression line.

#### y = 120.07 + -1.93x

(b) Interpret the slope in this context, and calculate the predicted birth weight of first borns and others.

#### The slope is -1.93 and is the difference in average weight in  ounces if the child is not the first born. If first born the child would way 120.07 ounces. If the child is not the firs born the average weight in ounces would be `r 120.07 + -1.93`

(c) Is there a statistically significant relationship between the average birth weight and parity? 

####At a p-value of .1052 there is not a significant relationship between average birth weight and parity.

8.4 Absenteeism. Researchers interested in the relationship between absenteeism from school and certain demographic characteristics of children collected data from 146 randomly sampled students in rural New SouthWales, Australia, in a particular school year. Below are three observations from this data set.


(a) Write the equation of the regression line.

#### y = 18.93 +-9.11x + 3.10x + 2.15x

(b) Interpret each one of the slopes in this context.

#### Each slope states how much absenteeism would change for change in each variable. For eth it is -9.11, sex 3.10 and lrn 2.15.

(c) Calculate the residual for the first observation in the data set: a student who is aboriginal, male, a slow learner, and missed 2 days of school.

#### y = `r 18.93 +-9.11*0 + 3.10 * 1 + 2.15 * 1`

(d) The variance of the residuals is 240.57, and the variance of the number of absent days for all students in the data set is 264.17. Calculate the R2 and the adjusted R2. Note that there are 146 observations in the data set.

####R2 = `r 240.57/264.17`

8.8 Absenteeism, Part II. Exercise 8.4 considers a model that predicts the number of days absent using three predictors: ethnic background (eth), gender (sex), and learner status (lrn). The table below shows the adjusted R-squared for the model as well as adjusted R-squared values for all models we evaluate in the first step of the backwards elimination process.

Which, if any, variable should be removed from the model first?

#### The no ethnicity variable should be removed as it has the lowest R2 value.

8.16 Challenger disaster, Part I. On January 28, 1986, a routine launch was anticipated for the Challenger space shuttle. Seventy-three seconds into the flight, disaster happened: the shuttle broke apart, killing all seven crew members on board. An investigation into the cause of the disaster focused on a critical seal called an O-ring, and it is believed that damage to these O-rings
during a shuttle launch may be related to the ambient temperature during the launch. The table below summarizes observational data on O-rings for 23 shuttle missions, where the mission order is based on the temperature at the time of the launch. Temp gives the temperature in Fahrenheit, Damaged represents the number of damaged O-rings, and Undamaged represents the number of O-rings that were not damaged.

(a) Each column of the table above represents a di???erent shuttle mission. Examine these data and describe what you observe with respect to the relationship between temperatures and damaged O-rings.

####It appears the lower the temparature the more likely the O-rings will be damaged.

(b) Failures have been coded as 1 for a damaged O-ring and 0 for an undamaged O-ring, and a logistic regression model was fit to these data. A summary of this model is given below. Describe the key components of this summary table in words.

####The intercept is the percentage of damaged 0-rings when at 53f. The temperature estimate is the slope which gives change in number of rings damaged per each raise in temperature. 

(c) Write out the logistic model using the point estimates of the model parameters.

####y = 11.6630 + -.2162x. the Value for 1 degree change is `r 11.6630 + -.2162 * 1`

(d) Based on the model, do you think concerns regarding O-rings are justified? Explain.

####Based on the low p-value the concerns regarding the o-rings are justified.

8.18 Challenger disaster, Part II. Exercise 8.16 introduced us to O-rings that were identified as a plausible explanation for the breakup of the Challenger space shuttle 73 seconds into takeo in 1986. The investigation found that the ambient temperature at the time of the shuttle launch was closely related to the damage of O-rings, which are a critical component of the shuttle. See this earlier exercise if you would like to browse the original data.

(a) The data provided in the previous exercise are shown in the plot. The logistic model fit to these data may be written as log where ^p is the model-estimated probability that an O-ring will become damaged. Use the model to calculate the probability that an O-ring will become damaged at each of the following
ambient temperatures: 51, 53, and 55 degrees Fahrenheit. The model-estimated probabilities for several additional ambient temperatures are provided below, where subscripts indicate the temperature

```{r}
11.6630 + -.2162 * 51
11.6630 + -.2162 * 53
11.6630 + -.2162 * 55


123.05 + (-8.94)*1

```

(b) Add the model-estimated probabilities from part (a) on the plot, then connect these dots usinga smooth curve to represent the model-estimated 


(c) Describe any concerns you may have regarding applying logistic regression in this application, and note any assumptions that are required to accept the model's validity.

####The assumptions for a models validity is that residuals are nearly normal, have constant variability, residuals are independent and each variable is linearly related to the outdcome. One concern is that the model may be missing a varible that has a stronger correlation or there are other confounding factors. 

