---
title: "Data 621 Exercise 6.1"
author: "Anthony Pagan"
date: "September 22, 2019"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Exercise 6.1

###Constant Variance assumption for errors
```{r}
data(sat, package='faraway')
lmod<- lm(total~expend+salary+ratio+takers,sat)
plot(fitted(lmod),residuals(lmod),xlab="Fitted",ylab="Residuals")
abline(h=0)
plot(sat$takers,residuals(lmod), xlab="takers",ylab="Residuals")
abline(h=0)
var.test(residuals(lmod),residuals(lmod)[sat$takers])
```

###Normality Assumption
```{r}
qqnorm(residuals(lmod),ylab="Residuals",main="")
qqline(residuals(lmod))
hist(residuals(lmod),xlab="Residuals",main="")
```

###Leverage Points
```{r}
hatv<- hatvalues(lmod)
head(hatv)
sum(hatv)
```

###Outliers
```{r}
set.seed(123)
testdata <- data.frame(x=1:10, y=1:10+rnorm(10))

p1<-c(5.5,12)
lmod1 <- lm(y ~x, rbind(testdata, p1))
plot(y ~ x, rbind(testdata, p1))
points(5.5,12,pch=4,cex=2)
abline(lmod)
abline(lmod1,lty=2)
```

###Influential Points
```{r}

plot(dfbeta(lmod)[,2],ylab="Change in takers coef")
abline(h=0)
```


###Structure of relationship between predictors and response
```{r}
summary(lmod)
d<-residuals(lm(total~expend+salary+ratio+takers,sat))
m<-residuals(lm(takers~expend+salary+ratio,sat))
plot(m,d,xlab="takers residuals",ylab="Sat Totals residuals")
abline(0,coef(lmod)['takers'])
```