---
title: "Data 698 Final Project"
author: "Anthony Pagan"
date: ""
output: 
    html_document:
        toc: true
        toc_float: true
        toc_depth: 5
        css: style.css
---

# Project Proposal

## Introduction


## Objective


## Methodology


# Data Description


```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)

rm(list=ls())
list.of.packages <- c("alluvial","caret","caret","corrplot","corrplot","data.table","dplyr","faraway","forcats","geosphere","ggplot2","ggplot2","ggplot2","grid","gridExtra","jtools","kableExtra","knitr","leaflet","leaflet.extras","leaps","lubridate","maps","MASS","mice","naniar","pander","patchwork","prettydoc","pROC","psych","RColorBrewer","readr","reshape2","scales","stringr","tibble","tidyr","tidyverse","xgboost","widgetframe","Rcpp","mlbench","fpp2","mlr","jsonlite","devtools","sparklyr","SparkR","readtext","magrittr","simmer","quanteda","tidytext","tm","SnowballC","text2vec","purrr","topicmodels","RMySQL")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages, dependencies=TRUE)

#knitr::opts_chunk$set(echo = TRUE)
require(knitr)
library(ggplot2)
library(tidyr)
library(MASS)
library(psych)
library(kableExtra)
library(dplyr)
library(faraway)
library(gridExtra)
library(reshape2)
library(leaps)
library(pROC)
library(caret)
library(naniar)
library(pander)
library(pROC)
library(mlbench)
library(e1071)
library(fpp2)
library(mlr)
library(recommenderlab)
library(jsonlite)
library(stringr)
library(devtools)
library(sparklyr)
library(readtext)
library(magrittr)
library(simmer)
library(quanteda)
library(tidytext)
library(tm)
library(SnowballC)
library(text2vec)
library(purrr)
library(topicmodels)
library(RMySQL)
```

# Import Data



```{r echo=TRUE, message=FALSE, warning=FALSE}
d1<- as.data.frame(read.csv('../Datasets/TestQuery.csv', header = TRUE))

cnames<-c('AlertName','AlertDescription','Severity','Priority','RaisedDateTime','ManagedEntityGuid')
d2<- as.data.frame(read.csv('../Datasets/TestQuery2.csv',header= FALSE, col.names = cnames ))

names(d1,d2)


```

# Review/Load Transform Data


```{r}
mydb = dbConnect(MySQL(), user='root', password='123456', dbname='data698', host='localhost')
dbListTables(mydb)
dbRemoveTable(mydb, "d1")
dbWriteTable(mydb, "d1",d1, overwrite = TRUE)
dbRemoveTable(mydb, "d2")
dbWriteTable(mydb, "d2",d2, overwrite = TRUE)

joineddata<-dbGetQuery(mydb, "select d.educator_id as EducatorD_ID, d.DISTRICT_NAME, s.Educator_id as EducatorS_ID, s.School_name, district_needs_category, per_pupil_expenditure,
d.overall_score, d.overall_rating, s.growth_rating from apprdstr d
inner join apprsch s on  d.district_beds = s.district_beds limit 1000000")
dbDisconnect(mydb)


```


# Data Exploration

```{r}

```



# Visualization

```{r}


```

# Modeling Testing

```{r}

```


# Test 

```{r}

```

# Predict

```{r}

```

# Model Selection

```{r}

```


# Conclusion



# Reference

# Appendix

**Code used in analysis**
```{r, ref.label=knitr::all_labels(),echo=TRUE,eval=FALSE}

```





